name: MacOS

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macos-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install GD
        run: brew install gd
      - name: Make GD reachable
        run: raku -e 'symlink "/opt/homebrew/lib/libgd.3.dylib".IO, $*EXECUTABLE.parent.sibling("lib/libgd.3.dylib")'
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Run Special Tests
        run: raku run-tests -i
